# -*- coding: utf-8 -*-
"""Daa _Practical_10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107VLhfL-i6XdmyRMFGXE7IUVnVV4jOev

Practical 10

Kruskals algorithm
"""

# Kruskal's Algorithm

# Find the parent of a vertex
def find(parent, vertex):
    if parent[vertex] != vertex:
        parent[vertex] = find(parent, parent[vertex])
    return parent[vertex]


# Join two sets
def union(parent, rank, u, v):
    root_u = find(parent, u)
    root_v = find(parent, v)

    if root_u != root_v:
        if rank[root_u] < rank[root_v]:
            parent[root_u] = root_v
        elif rank[root_u] > rank[root_v]:
            parent[root_v] = root_u
        else:
            parent[root_v] = root_u
            rank[root_u] += 1


def kruskal(vertices, edges):
    # Sort edges according to weight
    edges.sort(key=lambda x: x[2])

    # Initially, every vertex is its own parent
    parent = {v: v for v in vertices}
    rank = {v: 0 for v in vertices}

    mst = []
    total_cost = 0

    # Select edges one by one
    for u, v, weight in edges:

        # Check whether adding the edge creates a cycle
        if find(parent, u) != find(parent, v):

            mst.append((u, v, weight))
            total_cost += weight

            union(parent, rank, u, v)

        # MST contains V-1 edges
        if len(mst) == len(vertices) - 1:
            break

    return mst, total_cost


# Vertices
vertices = ['A', 'B', 'C', 'D', 'E']

# Edges: (vertex1, vertex2, weight)
edges = [
    ('A', 'B', 2),
    ('A', 'C', 3),
    ('B', 'C', 1),
    ('B', 'D', 4),
    ('C', 'D', 5),
    ('C', 'E', 6),
    ('D', 'E', 7)
]

# Apply Kruskal's Algorithm
mst, total_cost = kruskal(vertices, edges)

# Display result
print("Edges in Minimum Spanning Tree:")

for u, v, weight in mst:
    print(u, "-", v, ":", weight)

print("Total cost of MST:", total_cost)