# -*- coding: utf-8 -*-
"""DAA Practical 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IEr-XlaHziFKb7ZgoRY8W8v6Qv-jsYp4

Chain Matriix Multipication using Dynamic Programming
"""

import time

# Function for Matrix Chain Multiplication
def matrix_chain_order(p):
    n = len(p) - 1

    # m[i][j] stores minimum multiplication cost
    m = [[0] * (n + 1) for _ in range(n + 1)]

    # s[i][j] stores the position where the chain is split
    s = [[0] * (n + 1) for _ in range(n + 1)]

    # L is the chain length
    for L in range(2, n + 1):

        for i in range(1, n - L + 2):
            j = i + L - 1
            m[i][j] = float('inf')

            # Try every possible split
            for k in range(i, j):
                cost = (
                    m[i][k]
                    + m[k + 1][j]
                    + p[i - 1] * p[k] * p[j]
                )

                if cost < m[i][j]:
                    m[i][j] = cost
                    s[i][j] = k

    return m, s


# Function to print optimal parenthesization
def print_parenthesis(s, i, j):
    if i == j:
        return f"M{i}"

    k = s[i][j]

    left = print_parenthesis(s, i, k)
    right = print_parenthesis(s, k + 1, j)

    return f"({left} × {right})"


# -------------------------------
# Main Program
# -------------------------------

print("CHAIN MATRIX MULTIPLICATION USING DYNAMIC PROGRAMMING")
print("-" * 55)

# User input
n = int(input("Enter the number of matrices: "))

dimensions = []

print("\nEnter the dimensions of the matrices:")

for i in range(n):
    rows = int(input(f"Enter rows of Matrix M{i + 1}: "))
    cols = int(input(f"Enter columns of Matrix M{i + 1}: "))

    # Check compatibility
    if i > 0 and rows != dimensions[-1]:
        print("Error: Matrix dimensions are not compatible.")
        exit()

    dimensions.append(rows)
    dimensions.append(cols)

# Remove duplicate dimensions
p = [dimensions[0]]

for i in range(1, len(dimensions), 2):
    p.append(dimensions[i])

# Measure execution time
start_time = time.perf_counter()

m, s = matrix_chain_order(p)

end_time = time.perf_counter()

execution_time = end_time - start_time

# Display results
print("\n" + "-" * 55)
print("RESULT")
print("-" * 55)

print("Matrix Dimensions:")

for i in range(n):
    print(f"M{i + 1} = {p[i]} × {p[i + 1]}")

print("\nOptimal Parenthesization:")
print(print_parenthesis(s, 1, n))

print("\nMinimum Number of Scalar Multiplications:")
print(m[1][n])

print("\nTime Complexity: O(n³)")
print("Space Complexity: O(n²)")

print(f"Execution Time: {execution_time:.8f} seconds")