# -*- coding: utf-8 -*-
"""DAA_Practical_9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ity19i5zfdA5GU0gX4R4tTRFfjicyfhT

Prim’s  Algorithm
"""

# Prim's Algorithm

def prim(graph, start):
    visited = set()
    mst = []
    total_cost = 0

    # Start from the given vertex
    visited.add(start)

    while len(visited) < len(graph):
        min_edge = None
        min_weight = float('inf')

        # Find the minimum-weight edge
        # connecting visited and unvisited vertices
        for u in visited:
            for v, weight in graph[u]:
                if v not in visited and weight < min_weight:
                    min_weight = weight
                    min_edge = (u, v, weight)

        # If no edge is found, graph is disconnected
        if min_edge is None:
            print("Graph is not connected.")
            return

        u, v, weight = min_edge

        # Add edge to MST
        mst.append((u, v, weight))
        total_cost += weight

        # Mark the new vertex as visited
        visited.add(v)

    return mst, total_cost


# Graph represented using an adjacency list
graph = {
    'A': [('B', 2), ('C', 3)],
    'B': [('A', 2), ('C', 1), ('D', 4)],
    'C': [('A', 3), ('B', 1), ('D', 5), ('E', 6)],
    'D': [('B', 4), ('C', 5), ('E', 7)],
    'E': [('C', 6), ('D', 7)]
}

# Apply Prim's Algorithm
mst, total_cost = prim(graph, 'A')

# Display the result
print("Edges in Minimum Spanning Tree:")

for u, v, weight in mst:
    print(u, "-", v, ":", weight)

print("Total cost of MST:", total_cost)