# -*- coding: utf-8 -*-
"""DAA Practical 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODlx4Nx83oLnSJX-m5qFwl0nFL4QBufN

Practical 4

Implementation and Time analysis of factorial program using
iterative and recursive method
"""

import time

# Iterative method
def factorial_iterative(n):
    result = 1

    for i in range(1, n + 1):
        result = result * i

    return result


# Recursive method
def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial_recursive(n - 1)


# Taking input from user
n = int(input("Enter a number: "))

# Check for negative number
if n < 0:
    print("Factorial is not defined for negative numbers.")
else:
    # Iterative factorial and execution time
    start_time = time.perf_counter()
    iterative_result = factorial_iterative(n)
    end_time = time.perf_counter()

    iterative_time = end_time - start_time

    # Recursive factorial and execution time
    start_time = time.perf_counter()
    recursive_result = factorial_recursive(n)
    end_time = time.perf_counter()

    recursive_time = end_time - start_time

    # Display results
    print("\n========== FACTORIAL TIME ANALYSIS ==========")

    print("\nUser Input:", n)

    print("\n--- Iterative Method ---")
    print("Factorial:", iterative_result)
    print("Time Complexity: O(n)")
    print("Space Complexity: O(1)")
    print("Execution Time:", iterative_time, "seconds")

    print("\n--- Recursive Method ---")
    print("Factorial:", recursive_result)
    print("Time Complexity: O(n)")
    print("Space Complexity: O(n)")
    print("Execution Time:", recursive_time, "seconds")

    print("\n=============================================")