# -*- coding: utf-8 -*-
"""Lab Practical 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1-niJ1mbhCy3g269fHM1mYbCJFb3rgy

DAA

EXPERIMENT 1

A)SELECTION SORTING
"""

import time

# Function for Selection Sort
def selection_sort(arr, n):
    for i in range(n - 1):
        min_index = i

        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        # Swap elements
        temp = arr[i]
        arr[i] = arr[min_index]
        arr[min_index] = temp


# Main Program
n = int(input("Enter the number of elements: "))

arr = []

print("Enter the elements:")
for i in range(n):
    num = int(input())
    arr.append(num)

print("\nUser Input Array:")
for i in range(n):
    print(arr[i], end=" ")

# Start Execution Time
start = time.time()

selection_sort(arr, n)

# End Execution Time
end = time.time()

print("\n\nSorted Array:")
for i in range(n):
    print(arr[i], end=" ")

print("\n")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best Case    : O(n^2)")
print("Average Case : O(n^2)")
print("Worst Case   : O(n^2)")
print("Space Complexity : O(1)")

"""B) INSERTION SORTING"""

import time

# Function for Insertion Sort
def insertion_sort(arr, n):
    for i in range(1, n):
        key = arr[i]
        j = i - 1

        # Move elements greater than key one position ahead
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j = j - 1

        arr[j + 1] = key


# Main Program
n = int(input("Enter the number of elements: "))

arr = []

print("Enter the elements:")
for i in range(n):
    num = int(input())
    arr.append(num)

print("\nUser Input Array:")
for i in range(n):
    print(arr[i], end=" ")

# Start Execution Time
start = time.time()

# Perform Insertion Sort
insertion_sort(arr, n)

# End Execution Time
end = time.time()

print("\n\nSorted Array:")
for i in range(n):
    print(arr[i], end=" ")

print("\n")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best Case    : O(n)")
print("Average Case : O(n^2)")
print("Worst Case   : O(n^2)")
print("Space Complexity : O(1)")

"""C) BUBBLE SORTING"""

import time

# Function for Bubble Sort
def bubble_sort(arr, n):
    for i in range(n - 1):
        for j in range(n - 1 - i):
            if arr[j] > arr[j + 1]:
                # Swap elements
                temp = arr[j]
                arr[j] = arr[j + 1]
                arr[j + 1] = temp


# Main Program
n = int(input("Enter the number of elements: "))

arr = []

print("Enter the elements:")
for i in range(n):
    num = int(input())
    arr.append(num)

print("\nUser Input Array:")
for i in range(n):
    print(arr[i], end=" ")

# Start Execution Time
start = time.time()

# Perform Bubble Sort
bubble_sort(arr, n)

# End Execution Time
end = time.time()

print("\n\nSorted Array:")
for i in range(n):
    print(arr[i], end=" ")

print("\n")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best Case    : O(n)")
print("Average Case : O(n^2)")
print("Worst Case   : O(n^2)")
print("Space Complexity : O(1)")

"""D) MERGE SORTING"""

import time
# Function to Merge two subarrays
def merge(arr, left, mid, right):
    n1 = mid - left + 1
    n2 = right - mid

    L = [0] * n1
    R = [0] * n2

    # Copy data to temporary arrays
    for i in range(n1):
        L[i] = arr[left + i]

    for j in range(n2):
        R[j] = arr[mid + 1 + j]

    i = 0
    j = 0
    k = left

    # Merge the temporary arrays
    while i < n1 and j < n2:
        if L[i] <= R[j]:
            arr[k] = L[i]
            i = i + 1
        else:
            arr[k] = R[j]
            j = j + 1
        k = k + 1

    # Copy remaining elements of L[]
    while i < n1:
        arr[k] = L[i]
        i = i + 1
        k = k + 1

    # Copy remaining elements of R[]
    while j < n2:
        arr[k] = R[j]
        j = j + 1
        k = k + 1


# Function for Merge Sort
def merge_sort(arr, left, right):
    if left < right:
        mid = (left + right) // 2

        merge_sort(arr, left, mid)
        merge_sort(arr, mid + 1, right)

        merge(arr, left, mid, right)


# Main Program
n = int(input("Enter the number of elements: "))

arr = []

print("Enter the elements:")
for i in range(n):
    num = int(input())
    arr.append(num)

print("\nUser Input Array:")
for i in range(n):
    print(arr[i], end=" ")

# Start Execution Time
start = time.time()

# Perform Merge Sort
merge_sort(arr, 0, n - 1)

# End Execution Time
end = time.time()

print("\n\nSorted Array:")
for i in range(n):
    print(arr[i], end=" ")

print("\n")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")
print("Space Complexity : O(n)")

"""E) QUICK SORTING"""

import time

# Function to partition the array
def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1

    for j in range(low, high):
        if arr[j] <= pivot:
            i = i + 1

            # Swap elements
            temp = arr[i]
            arr[i] = arr[j]
            arr[j] = temp

    # Place pivot in correct position
    temp = arr[i + 1]
    arr[i + 1] = arr[high]
    arr[high] = temp

    return i + 1


# Function for Quick Sort
def quick_sort(arr, low, high):
    if low < high:
        pi = partition(arr, low, high)

        quick_sort(arr, low, pi - 1)
        quick_sort(arr, pi + 1, high)


# Main Program
n = int(input("Enter the number of elements: "))

arr = []

print("Enter the elements:")
for i in range(n):
    num = int(input())
    arr.append(num)

print("\nUser Input Array:")
for i in range(n):
    print(arr[i], end=" ")

# Start Execution Time
start = time.time()

# Perform Quick Sort
quick_sort(arr, 0, n - 1)

# End Execution Time
end = time.time()

print("\n\nSorted Array:")
for i in range(n):
    print(arr[i], end=" ")

print("\n")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n^2)")
print("Space Complexity : O(log n)")