# -*- coding: utf-8 -*-
"""Practical 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuY5VAKoz9bnsg0NvWPLk8PBss6pa_UL

Maxheap sorting
"""

import time

# Function to maintain the Max Heap
def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2
    # Check left child
    if left < n and arr[left] > arr[largest]:
        largest = left
    # Check right child
    if right < n and arr[right] > arr[largest]:
        largest = right
    # If largest is not the root
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        # Recursively heapify the affected subtree
        heapify(arr, n, largest)
# Max Heap Sort
def max_heap_sort(arr):
    n = len(arr)
    # Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)
    # Extract elements one by one
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        # Heapify the reduced heap
        heapify(arr, i, 0)
n = int(input("Enter number of elements: "))
arr = []
for i in range(n):
    value = int(input("Enter element " + str(i + 1) + ": "))
    arr.append(value)
print("\nUser Input:", arr)
# Start execution time
start_time = time.perf_counter()
# Perform Max Heap Sort
max_heap_sort(arr)
# End execution time
end_time = time.perf_counter()
# Calculate execution time
execution_time = end_time - start_time
print("Sorted Array:", arr)
print("Time Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")
print("Execution Time:", execution_time, "seconds")