# -*- coding: utf-8 -*-
"""Practical 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFm5rHzepuqere3yZbU_19OYal0gqbzN

Practical 2

1) linear search :

     Linear Search is a method of searching where each element is checked one by one until the required element is found or the list ends.
"""

import time

# Input: Number of elements
n = int(input("Enter the number of elements: "))

# Input: List elements
arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

# Input: Element to search
key = int(input("Enter the element to search: "))

# Start timer
start_time = time.perf_counter()

# Sequential Search
found = False
position = -1

for i in range(n):
    if arr[i] == key:
        found = True
        position = i
        break

# End timer
end_time = time.perf_counter()

# Output
print("\nUser Input Array:", arr)
print("Element Searched:", key)

if found:
    print(f"Element found at position {position + 1}")
else:
    print("Element not found")

# Execution time
execution_time = end_time - start_time
print(f"Execution Time: {execution_time:.10f} seconds")

# Time Complexity
print("\nTime Complexity:")
print("Best Case   : O(1)")
print("Average Case: O(n)")
print("Worst Case  : O(n)")

"""2)Binary search:

  Binary Search is a searching method that repeatedly divides a sorted list into two halves to find the required element quickly.
"""

import time

# Input
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements in sorted order:")
for i in range(n):
    arr.append(int(input()))

key = int(input("Enter the element to search: "))

# Start timer
start = time.perf_counter()

# Binary Search
low = 0
high = n - 1
found = False

while low <= high:
    mid = (low + high) // 2

    if arr[mid] == key:
        found = True
        position = mid
        break
    elif arr[mid] < key:
        low = mid + 1
    else:
        high = mid - 1

# End timer
end = time.perf_counter()

# Output
print("\nUser Input Array:", arr)
print("Element Searched:", key)

if found:
    print("Element found at position", position + 1)
else:
    print("Element not found")

print("Execution Time:", end - start, "seconds")

print("\nTime Complexity:")
print("Best Case   : O(1)")
print("Average Case: O(log n)")
print("Worst Case  : O(log n)")